name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'   # It only run if there's change in index.html

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed for push of gh-pages branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
